### PR TITLE
Feature/turbo frame support

### LINKED ISSUE #36: after fired turbo:render x-data not exists
Hi guys, thanks for the connector, but a found a little issue:

I had this form:
image
as you can see the alpinejs works at the beginning. when the form submitted is succeed turbo reload the complete page.

image
and the alpinejs not working ....

What happened ?

The turbo:render fired but not found any dom node related alpine  `document.querySelectorAll('[x-data]')`

If I put on console the snippet

```
      window.Alpine.discoverUninitializedComponents((el) => {
        window.Alpine.initializeComponent(el)
      })
```
Now the alpinejs works...

TLDR; when turbo:render the ``document.querySelectorAll('[x-data]')` return empty  and the window.Alpine.initializeComponent never happened.

image

### PR DESCRIPTION
**Pull request by SimoTod**
Fixes #36

### CODE REVIEW

**Comment by BentoumiTech** [comment]
Hi @SimoTod I was having issue with turbo frame and alpine using this branch it works great, any reason why you haven't merged it yet ?

**Review by BentoumiTech — APPROVED** [review]

**Comment by BentoumiTech** [comment]
Actually not sure why but the min version you posted here https://cdn.jsdelivr.net/gh/simotod/alpine-turbo-drive-adapter@feature/turbo-frame-support/dist/alpine-turbo-drive-adapter.min.js works but the branch didn't work on my machine

**Comment by SimoTod** [comment]
@BentoumiTech no specific reason. I asked for feedback and the guy who originally asked for the feature never replied. I wasn't too confident it was working correctly at that time so I never merged it in.

**Comment by SimoTod** [comment]
Closed as it probably had a bug. If it's still a problem in V3, I'll look for a different solution

**Pull request closed without merging**
